"use client";

import { ChangeEvent, useMemo, useState } from "react";

type NoiseRow={timestamp:Date;interval:number;leq:number;peak:number;battery:number;temperature:number|null;humidity:number|null;wind:number|null};
type View="intro"|"loading"|"dashboard";
type Metric="leq"|"peak";
const FALLBACK=[-68.7,-67.1,-61.7,-55.8,-55.1,-52.8,-56.3,-57.4,-54.2,-60.1,-63.7,-58.8,-53.1,-50.4,-56.9,-58.1,-49.7,-45.4,-55.8,-61.2];
const dateKey=(d:Date)=>d.toLocaleDateString("en-CA",{timeZone:"Europe/London"});
const percentile=(values:number[],p:number)=>{const s=[...values].sort((a,b)=>a-b);return s[Math.round((s.length-1)*p)]};

function parseCsv(text:string):NoiseRow[]{
  const lines=text.trim().split(/\r?\n/).filter(Boolean),keys=lines[0]?.split(",").map(k=>k.trim().replace(/^\uFEFF/,""))??[];
  if(!keys.includes("timestamp_utc_iso")||!keys.includes("leq_dbfs")||!keys.includes("peak_dbfs"))throw new Error("CSV must include timestamp_utc_iso, leq_dbfs and peak_dbfs.");
  return lines.slice(1).map(line=>{const values=line.split(",").map(v=>v.trim()),item=Object.fromEntries(keys.map((key,i)=>[key,values[i]]));const optional=(k:string)=>item[k]?Number(item[k]):null;return{timestamp:new Date(item.timestamp_utc_iso),interval:Number(item.interval_seconds)||0,leq:Number(item.leq_dbfs),peak:Number(item.peak_dbfs),battery:Number(item.battery_percent),temperature:optional("temperature_c"),humidity:optional("humidity_percent"),wind:optional("wind_speed_mps")}}).filter(r=>!Number.isNaN(r.timestamp.getTime())&&Number.isFinite(r.leq)&&Number.isFinite(r.peak)).sort((a,b)=>a.timestamp.getTime()-b.timestamp.getTime());
}

function DailyChart({data,metric,selected}:{data:NoiseRow[];metric:Metric;selected:string}){
  const width=1160,height=390,pad={l:58,r:18,t:18,b:42},bins=144;
  const series=useMemo(()=>{const grouped=new Map<string,number[][]>();data.forEach(row=>{const k=dateKey(row.timestamp);if(!grouped.has(k))grouped.set(k,Array.from({length:bins},()=>[]));const parts=new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Europe/London"}).formatToParts(row.timestamp);const hour=Number(parts.find(p=>p.type==="hour")?.value??0)%24,minute=Number(parts.find(p=>p.type==="minute")?.value??0),bin=Math.min(bins-1,Math.floor((hour*60+minute)/10));grouped.get(k)![bin].push(row[metric]);});return [...grouped].map(([key,values])=>({key,values:values.map(v=>v.length?percentile(v,.5):null)}));},[data,metric]);
  const allValues=data.map(d=>d[metric]),yMin=Math.floor((Math.min(...allValues)-4)/10)*10,yMax=Math.ceil((Math.max(...allValues)+4)/10)*10;
  const median=Array.from({length:bins},(_,i)=>{const vals=series.map(s=>s.values[i]).filter((v):v is number=>v!==null);return vals.length?percentile(vals,.5):null});
  const x=(i:number)=>pad.l+i/(bins-1)*(width-pad.l-pad.r),y=(v:number)=>pad.t+(yMax-v)/(yMax-yMin)*(height-pad.t-pad.b);
  const path=(values:(number|null)[])=>{let open=false;return values.map((v,i)=>{if(v===null){open=false;return""}const command=open?"L":"M";open=true;return`${command}${x(i).toFixed(1)},${y(v).toFixed(1)}`}).join(" ")};
  const ticks=Array.from({length:5},(_,i)=>yMin+(yMax-yMin)*i/4);
  return <svg className="daily-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric==="leq"?"Leq":"Peak"} sound levels across a 24-hour day`}>
    {ticks.map(v=><g key={v}><line x1={pad.l} x2={width-pad.r} y1={y(v)} y2={y(v)} className="chart-grid"/><text x={pad.l-12} y={y(v)+4} textAnchor="end">{v.toFixed(0)}</text></g>)}
    {[0,3,6,9,12,15,18,21,24].map(h=><g key={h}><line x1={pad.l+h/24*(width-pad.l-pad.r)} x2={pad.l+h/24*(width-pad.l-pad.r)} y1={pad.t} y2={height-pad.b} className="chart-grid vertical-grid"/><text x={pad.l+h/24*(width-pad.l-pad.r)} y={height-13} textAnchor={h===0?"start":h===24?"end":"middle"}>{String(h).padStart(2,"0")}:00</text></g>)}
    {series.map(s=><path key={s.key} d={path(s.values)} className={s.key===selected?"day-line selected-day":"day-line"}/>)}
    <path d={path(median)} className="median-line"/><text x="14" y="22" className="axis-title">dBFS</text>
  </svg>
}

function Loading(){return <main className="loading-screen"><div className="liquid-shell"><div className="liquid-core"/><div className="liquid-glint"/><span>Reading your soundscape</span></div><p>Organising measurements from midnight to midnight</p></main>}

export default function Home(){
  const [view,setView]=useState<View>("intro"),[data,setData]=useState<NoiseRow[]>([]),[fileName,setFileName]=useState(""),[fileError,setFileError]=useState(""),[metric,setMetric]=useState<Metric>("leq"),[selected,setSelected]=useState("");
  const enter=(rows:NoiseRow[],name:string)=>{setData(rows);setFileName(name);setSelected(dateKey(rows[0].timestamp));setView("loading");window.scrollTo(0,0);window.setTimeout(()=>setView("dashboard"),1500)};
  const loadFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setFileError("");try{const rows=parseCsv(await file.text());if(!rows.length)throw new Error("No valid noise readings were found.");enter(rows,file.name)}catch(error){setFileError(error instanceof Error?error.message:"This CSV could not be read.");e.target.value=""}};
  const loadDemo=()=>enter(FALLBACK.map((leq,i)=>({timestamp:new Date(Date.UTC(2026,7,17,21,50,i*5)),interval:5,leq,peak:leq+22,battery:85,temperature:23.7,humidity:56,wind:3.8})),"sample-noise.csv");
  const dates=useMemo(()=>[...new Set(data.map(r=>dateKey(r.timestamp)))],[data]);
  const selectedRows=data.filter(r=>dateKey(r.timestamp)===selected),visible=selectedRows.length?selectedRows:data;
  const stats=useMemo(()=>{if(!visible.length)return null;const vals=visible.map(r=>r.leq),duration=visible.reduce((s,r)=>s+r.interval,0),median=percentile(vals,.5),peaks=visible.map(r=>r.peak);return{median,energy:10*Math.log10(vals.reduce((s,v)=>s+10**(v/10),0)/vals.length),peak:Math.max(...peaks),range:percentile(vals,.9)-percentile(vals,.1),coverage:duration/60,events:visible.filter(r=>r.leq>=median+6).length}},[visible]);
  if(view==="loading")return <Loading/>;
  if(view==="intro")return <main className="portal"><nav className="portal-nav"><a className="frontera" href="#opening"><span className="frontera-mark"><i/><i/><i/></span><span>Frontera<br/>Data Labs</span></a><span>HOME NOISE / 001</span><span className="portal-status"><i/> LOCAL DATA</span></nav><section id="opening" className="portal-hero"><div className="signal-sky" aria-hidden="true"><i/><i/><i/><i/><i/></div><p className="portal-kicker">THE CITY IS ALWAYS SPEAKING</p><h1>Explore the vital signs<br/><em>around your home.</em></h1><p className="portal-copy">Turn sound measurements into a living view of the rhythms, interruptions and quiet moments shaping your environment.</p><a className="portal-scroll" href="#begin"><span>SCROLL TO BEGIN</span><i/></a><div className="portal-foot"><span>TIME-AVERAGED SOUND · LEQ</span><span>INSTANTANEOUS PEAK · dBFS</span><span>PRIVATE BY DESIGN</span></div></section><section id="begin" className="begin-section"><div className="begin-grid" aria-hidden="true"/><div className="begin-orbit orbit-one"/><div className="begin-orbit orbit-two"/><p className="portal-kicker">YOUR DATA · YOUR ENVIRONMENT</p><h2>Ready to begin?</h2><p>Select a StreetNoise Monitor CSV. It is processed locally in this browser and is never uploaded.</p><label className="file-button"><input type="file" accept=".csv,text/csv" onChange={loadFile}/><span>Choose noise CSV</span><b>↗</b></label><button className="demo-button" onClick={loadDemo}>or explore the sample capture</button>{fileError&&<div className="file-error" role="alert">{fileError}</div>}<div className="required-fields"><span>REQUIRED FIELDS</span><b>timestamp_utc_iso</b><b>leq_dbfs</b><b>peak_dbfs</b></div></section></main>;
  return <main className="dashboard-shell">
    <aside className="sidebar"><a className="frontera dashboard-logo" href="#"><span className="frontera-mark"><i/><i/><i/></span><span>Frontera<br/>Data Labs</span></a><nav><a className="active" href="#overview"><span>⌁</span>Overview</a><a href="#daily"><span>⌇</span>Daily dynamics</a><a href="#insights"><span>◇</span>Insights</a><a href="#data"><span>⊞</span>Data quality</a></nav><div className="side-bottom"><small>SENSOR</small><b><i/> Home 01</b><span>Local CSV</span></div></aside>
    <section className="dashboard-main" id="overview"><header className="dash-header"><div><p>HOME ENVIRONMENT</p><h1>Noise dynamics</h1></div><div className="header-actions"><div className="file-pill"><span>{fileName}</span><small>{data.length.toLocaleString()} readings</small></div><button onClick={()=>{setView("intro");setData([]);window.scrollTo(0,0)}}>Change CSV</button></div></header>
      <div className="summary-grid"><article><span>Energy average</span><strong>{stats?.energy.toFixed(1)}<small>dBFS</small></strong><p>Logarithmic mean for selection</p></article><article><span>Median Leq</span><strong>{stats?.median.toFixed(1)}<small>dBFS</small></strong><p>Typical relative sound level</p></article><article><span>Maximum peak</span><strong>{stats?.peak.toFixed(1)}<small>dBFS</small></strong><p>Highest instantaneous digital peak</p></article><article><span>Observed time</span><strong>{stats?.coverage.toFixed(1)}<small>min</small></strong><p>{selectedRows.length} measurements</p></article></div>
      <section className="dashboard-card chart-card" id="daily"><div className="card-head"><div><p>24-HOUR PROFILE</p><h2>Daily sound distribution</h2><span>Soft grey: every recorded day · Black: median across days · Green: selected day</span></div><div className="metric-toggle"><button className={metric==="leq"?"on":""} onClick={()=>setMetric("leq")}>Leq</button><button className={metric==="peak"?"on":""} onClick={()=>setMetric("peak")}>Peak</button></div></div><div className="date-selector"><button className={selected==="all"?"selected":""} onClick={()=>setSelected("all")}><b>ALL</b><span>Median view</span></button>{dates.map(k=>{const d=new Date(`${k}T12:00:00`);return <button key={k} className={selected===k?"selected":""} onClick={()=>setSelected(k)}><b>{d.toLocaleDateString("en-GB",{weekday:"short"}).toUpperCase()}</b><span>{d.toLocaleDateString("en-GB",{day:"2-digit",month:"short"})}</span></button>})}</div><DailyChart data={data} metric={metric} selected={selected}/><div className="chart-note"><i/> Empty parts of the timeline are unobserved. The dashboard never fills or interpolates gaps.</div></section>
      <div className="lower-grid"><section className="dashboard-card" id="insights"><div className="card-head"><div><p>RELATIVE INSIGHTS</p><h2>What changed?</h2></div><span className="status-tag">dBFS · NOT CALIBRATED SPL</span></div><div className="insight-list"><article><i>01</i><div><b>{stats?.range.toFixed(1)} dB acoustic spread</b><p>The L10–L90 difference describes how variable the selected soundscape was.</p></div></article><article><i>02</i><div><b>{stats?.events} elevated readings</b><p>Measurements at least 6 dB above this selection’s median; consecutive readings are not yet merged into events.</p></div></article><article><i>03</i><div><b>Health thresholds remain locked</b><p>dBFS cannot be compared with WHO dB(A) guidance until the phone is calibrated and A-weighting is implemented.</p></div></article></div></section><section className="dashboard-card" id="data"><div className="card-head"><div><p>CAPTURE QUALITY</p><h2>Data coverage</h2></div></div><div className="coverage-visual"><div className="coverage-clock"><span style={{"--coverage":Math.min(100,(stats?.coverage??0)/1440*100)} as React.CSSProperties}/><b>{((stats?.coverage??0)/1440*100).toFixed(2)}%</b><small>of selected day</small></div><div><p><span>Readings</span><b>{visible.length}</b></p><p><span>Interval</span><b>{visible[0]?.interval??"—"} sec</b></p><p><span>Weather</span><b>{visible.filter(r=>r.temperature!==null).length} rows</b></p></div></div></section></div>
    </section>
  </main>
}
